### ISSUE TITLE
Do you have an example for Writing to a Parquet file like your PowerShell read example.

### ISSUE THREAD

**Issue by lostsole** [Apteco/HelperScripts#1]
Does anyone have a PowerShell Example for writing to a Parquet file?
Like the https://github.com/Apteco/HelperScripts/blob/master/scripts/parquet/parquet_read.ps1 script but one for Writing(parquet_write.ps1)

I am new to Parquet files

**Comment by gitfvb** [comment]
Hi @lostsole, sorry, I have only seen your request now. No, I don't have experience in that space. Good luck!
